# shared baseline for recipes in this repo, based on conda-forge-pinning:
# https://github.com/conda-forge/conda-forge-pinning-feedstock
c_stdlib:
  - if: linux
    then: sysroot
  - if: osx
    then: macosx_deployment_target
  - if: win
    then: vs

c_stdlib_version:
  - if: linux
    then: 2.17
  - if: osx
    then: 11.0

c_compiler:
  - if: linux
    then: gcc
  - if: osx
    then: clang
  - if: win
    then: vs
c_compiler_version:
  - if: linux
    then: 15
  - if: osx
    then: 21
  # We use GitHub Actions to build packages, see `.github/matrix.json`. Ensure
  # the vs compiler is synced with the one provided in GitHub Actions runner images:
  # https://github.com/actions/runner-images/tree/main#available-images
  - if: win
    then: 2022

cxx_compiler:
  - if: linux
    then: gxx
  - if: osx
    then: clangxx
  - if: win
    then: vs
cxx_compiler_version:
  - if: linux
    then: 15
  - if: osx
    then: 21
  - if: win
    then: 2022
