schema_version: 1

context:
  name: nano
  version: "9.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://www.nano-editor.org/dist/v${{ (version | split('.'))[0] }}/nano-${{ version }}.tar.xz
    sha256: 9f384374b496110a25b73ad5a5febb384783c6e3188b37063f677ac908013fde
    patches:
      - if: win
        then:
        - 0001-win32-include-windows-header.patch
        - 0002-win32-drop-bracketed-paste-mode-escape-sequences.patch
        - 0003-win32-system-wide-rcfile-compat.patch
        - 0004-win32-fix-file-parentdir-access.patch
        - 0005-win32-replace-slashes-and-invalid-filename-chars.patch
        - 0006-win32-homedir-tempdir-compat.patch
        - 0007-win32-file-io-to-binary-mode.patch
        - 0008-win32-utf8-support-and-detect-wide-char-width.patch
        - 0009-win32-windows-conhost-read-stdin-data.patch
        - 0010-win32-remove-halfdelay-for-unicode.patch
        - 0011-win32-keycode-pdcursesmod-compat.patch
        - 0012-win32-colortype-pdcursesmod-compat.patch
        - 0013-win32-window-resize-handling-and-screen-redraw.patch
        - 0014-win32-formatter-and-spell-check-support.patch
        - 0015-win32-poshistory-item-windows-path-compat.patch # v8.5+
        - 0016-win32-pdcursesmod-ctrlv-passthrough.patch
  - if: win and build_platform != 'win-64' and build_platform != 'win-arm64'
    then:
      - path: autogen.sh
      - git: https://github.com/coreutils/gnulib.git
        rev: "b75134c814c38876f04029ffc3fae4e90035dc34"
        depth: 2222
        target_directory: gnulib
  - path: branding.sh

build:
  number: 0

requirements:
  build:
    - if: target_platform == 'win-arm64' or target_platform == 'win-32'
      then:
        - llvm-mingw
      else:
        - ${{ compiler('c') }}
    - make
    - pkg-config
    - if: build_platform == 'win-64' or build_platform == 'win-arm64'
      then:
        - m2-bash
        - m2-coreutils
        - m2-sed
        - m2-gawk
        - m2-grep
      else:
        - autoconf
        - automake
        - gettext-tools
  host:
    - if: win
      then: mingw-w64-pdcursesmod-static
      else: ncurses

tests:
  - script:
    - if: build_platform == target_platform
      then: nano -h
  - package_contents:
      bin:
        - nano
      files:
        - etc/nanorc

about:
  homepage: https://www.nano-editor.org
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Nano's ANOther text editor, inspired by Pico
  repository: https://cgit.git.savannah.gnu.org/cgit/nano.git/
  description: |
    Nano is a small and simple text editor for use on the terminal.
    It copied the interface and key bindings of the Pico editor but
    added several missing features: undo/redo, syntax highlighting,
    line numbers, softwrapping, multiple buffers, selecting text by
    holding Shift, search-and-replace with regular expressions, and
    several other conveniences.
  documentation: https://github.com/chawyehsu/nano-for-windows

extra:
  recipe-maintainers:
    - chawyehsu
