schema_version: 1

context:
  name: nano
  version: "8.7.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://www.nano-editor.org/dist/v${{ (version | split('.'))[0] }}/nano-${{ version }}.tar.xz
    sha256: 76f0dcb248f2e2f1251d4ecd20fd30fb400a360a3a37c6c340e0a52c2d1cdedf
    patches:
      - if: win
        then:
        - 0000-include-windows-header.patch
        - 0001-drop-bracketed-paste-mode-escape-sequences.patch
        - 0002-system-wide-rcfile-compat.patch
        - 0003-fix-file-parentdir-access.patch
        - 0004-replace-slashes-and-invalid-filename-chars.patch
        - 0005-homedir-tempdir-compat.patch
        - 0006-file-io-to-binary-mode.patch
        - 0007-utf8-support-and-wide-char-width-detection-fix.patch
        - 0008-windows-conhost-read-stdin-data.patch
        - 0009-remove-halfdelay-for-unicode.patch
        - 0010-keycode-pdcursesmod-compat.patch
        - 0011-colortype-pdcursesmod-compat.patch
        - 0012-poshistory-item-windows-path-compat.patch # v8.5+
        - 0013-pdcursesmod-ctrlv-passthrough.patch
  - path: autogen.sh
  - path: branding.sh

build:
  number: 2

requirements:
  build:
    - ${{ compiler('c') }}
    - make
    - pkg-config
    - if: build_platform == 'win-64' or build_platform == 'win-arm64'
      then:
        - m2-bash
        - m2-coreutils
        - m2-sed
        - m2-gawk
        - m2-grep
      else:
        - autoconf
        - automake
        - gettext-tools
  host:
    - if: win
      then: mingw-w64-pdcursesmod-static
      else: ncurses

tests:
  - script:
    - if: build_platform == target_platform
      then: nano -h
  - package_contents:
      bin:
        - if: win
          then: nano.exe
          else: nano
      files:
        - etc/nanorc

about:
  homepage: https://www.nano-editor.org
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Nano's ANOther text editor, inspired by Pico
  repository: https://cgit.git.savannah.gnu.org/cgit/nano.git/
  description: |
    Nano is a small and simple text editor for use on the terminal.
    It copied the interface and key bindings of the Pico editor but
    added several missing features: undo/redo, syntax highlighting,
    line numbers, softwrapping, multiple buffers, selecting text by
    holding Shift, search-and-replace with regular expressions, and
    several other conveniences.
  documentation: https://github.com/chawyehsu/conda-recipes/blob/main/nano/README.md

extra:
  recipe-maintainers:
    - chawyehsu
