schema_version: 1

context:
  name: mihoro
  version: "0.12.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/spencerwooo/mihoro/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 8002ef168357dc35a1e5df61c39e5de65f4913aba45b080f491b5b474496c5bf
    patches:
    - if: osx
      then:
        - 0001-feat-macos-support.patch

build:
  number: 0
  skip:
    - win
  script:
    # Disable `self_update` feature for conda variant builds
    - cargo install --locked --root ${{ PREFIX }} --path . --no-track --no-default-features

requirements:
  build:
    - ${{ compiler("rust") }}

tests:
  - script:
    - if: build_platform == target_platform
      then: mihoro -V

about:
  homepage: https://github.com/spencerwooo/mihoro
  license: MIT
  license_file: LICENSE
  summary: Mihomo CLI client, no more, no less
  description: Mihomo CLI client, no more, no less
  repository: https://github.com/spencerwooo/mihoro

extra:
  recipe-maintainers:
    - chawyehsu
