schema_version: 1

context:
  name: mihoro
  version: "0.10.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/spencerwooo/mihoro/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 0bd82a4a0d68a77d0ee7f4c49df3256eaca844293752075016d32d5f1eff920e
    patches:
    - if: osx
      then:
        - 0001-macos-support.patch

build:
  number: 0
  skip:
    - win
  script:
    # Disable `self_update` feature for conda variant builds
    - cargo install --locked --root ${{ PREFIX }} --path . --no-track --no-default-features

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}

tests:
  - script:
    - if: build_platform == target_platform
      then: mihoro -V

about:
  homepage: https://github.com/spencerwooo/mihoro
  license: MIT
  license_file: LICENSE
  summary: Mihomo CLI client on Linux
  description: Mihomo CLI client on Linux
  repository: https://github.com/spencerwooo/mihoro

extra:
  recipe-maintainers:
    - chawyehsu
