schema_version: 1

context:
  name: cargo-binstall
  version: "1.17.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/cargo-bins/cargo-binstall/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 4d03768ef4bd89f387d9a557b6780c492cebb70dbf54fe33400fee8e82dea588
  patches:
    - if: win and build_platform != target_platform
      then: 0001-cross-compile-rc.patch

build:
  number: 0
  script:
    - if: win
      then: |
        set AWS_LC_SYS_CFLAGS=/std:c11 /experimental:c11atomics
        set AWS_LC_SYS_NO_JITTER_ENTROPY=1
    - if: build_platform == 'win-64' and target_platform == 'win-arm64'
      then: |
        set "CARGO_TARGET_DIR=C:\tmp\cargo-target"
        set "CARGO_BUILD_TARGET=aarch64-pc-windows-msvc"
    - cargo install --locked --root ${{ PREFIX }} --path crates/bin --no-track
    - cargo-bundle-licenses --format yaml --output ${{ SRC_DIR }}/THIRDPARTY.yml

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}
    - cargo-bundle-licenses

tests:
  - script:
      - if: build_platform == target_platform
        then: cargo-binstall -V

about:
  homepage: https://github.com/cargo-bins/cargo-binstall
  license: GPL-3.0-only
  license_file:
    - crates/bin/LICENSE
    - THIRDPARTY.yml
  summary: Binary installation for rust projects
  description: |
    Binstall provides a low-complexity mechanism for installing Rust binaries
    as an alternative to building from source (via cargo install) or manually
    downloading packages
  repository: https://github.com/cargo-bins/cargo-binstall

extra:
  recipe-maintainers:
    - chawyehsu
