schema_version: 1

context:
  name: bear
  version: "4.0.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/rizsotto/Bear/archive/refs/tags/${{ version }}.tar.gz
    sha256: 99a03b33cb762391d7122ca05ef41f2029cbe9bc43f23e7068dee88637c5b269
    patches:
      - 0001-wrapper-relative-path-support.patch

build:
  number: 0
  script:
    - cargo install --locked --root ${{ PREFIX }} --path bear --no-track
    - cargo install --locked --root ${{ PREFIX }} --path intercept-wrapper --no-track
    - if: build_platform == 'win-64' or build_platform == 'win-arm64'
      then:
        - mkdir ${{ PREFIX }}\libexec\bear
        - move ${{ PREFIX }}\bin\wrapper.exe ${{ PREFIX }}\libexec\bear
      else:
        - mkdir -p ${{ PREFIX }}/libexec/bear
        - mv ${{ PREFIX }}/bin/wrapper ${{ PREFIX }}/libexec/bear
    - if: linux
      then:
        - cargo build --release --lib --manifest-path=intercept-preload/Cargo.toml
        - cp target/*/release/libexec.so ${{ PREFIX }}/libexec/bear

requirements:
  build:
    - ${{ compiler("rust") }}

tests:
  - package_contents:
      bin:
        - if: win
          then: bear.exe
          else: bear
      files:
        - if: win
          then: libexec\bear\wrapper.exe
          else: libexec/bear/wrapper
        - if: linux
          then: libexec/bear/libexec.so
  - if: build_platform == target_platform
    then:
      script:
        - bear -V
        - bear -- make --version
        - if: build_platform == 'win-64' or build_platform == 'win-arm64'
          then: type compile_commands.json
          else: test -f compile_commands.json
      requirements:
        run:
          - make

about:
  homepage: https://github.com/rizsotto/Bear
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: A tool that generates a compilation database for clang tooling
  description: A tool that generates a compilation database for clang tooling.
  repository: https://github.com/rizsotto/Bear

extra:
  recipe-maintainers:
    - chawyehsu
