schema_version: 1

context:
  name: lumen
  version: "2.20.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/jnsahaj/lumen/archive/refs/tags/v${{ version }}.tar.gz
  sha256: c077740d0f04f6207850f8e3569984e6d6c6decff0272996ba012b52eef9b884

build:
  number: 0
  script:
    # use clang for `ring`, see: https://github.com/briansmith/ring/issues/2215
    - if: build_platform == 'win-64' and target_platform == 'win-arm64'
      then: |
        set "CARGO_TARGET_DIR=C:\tmp\cargo-target"
        set "CARGO_BUILD_TARGET=aarch64-pc-windows-msvc"
    - cargo install --locked --root ${{ PREFIX }} --path . --no-track

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}

tests:
  - script:
    - if: build_platform == target_platform
      then: lumen -V

about:
  homepage: https://github.com/jnsahaj/lumen
  license: MIT
  license_file: LICENSE
  summary: CLI tool to generate commit messages, summarise git diffs with AI
  description: |
    A command-line tool that uses AI to streamline your git workflow
    generate commit messages, view diff and explain changes.
  repository: https://github.com/jnsahaj/lumen

extra:
  recipe-maintainers:
    - chawyehsu
