schema_version: 1

context:
  name: moonup
  version: "0.2.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/chawyehsu/moonup/archive/refs/tags/v${{ version }}.tar.gz
  sha256: d2c98d0c52d95780da51f50d01b7dcc7c9e976a2a7e9bb31e5f0e3e40e9a5ac8

build:
  number: 0
  skip:
    # remove when moonbit adds support for these targets
    - win and arm64
    - linux and aarch64
  script:
    # [win] disable default static linked executables
    - if: win
      then: del /S /Q .cargo\config.toml
    # Disable `self_update` feature for conda variant builds
    - cargo install --locked --root ${{ PREFIX }} --path . --no-track --no-default-features

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}
  host:
    - if: linux
      then: openssl

tests:
  - script:
      - moonup --help

about:
  homepage: https://github.com/chawyehsu/moonup
  license: Apache-2.0
  license_file: LICENSE
  summary: "Manage multiple MoonBit installations"
  description: "Moonup is a version manager for MoonBit"
  repository: https://github.com/chawyehsu/moonup

extra:
  recipe-maintainers:
    - chawyehsu
