schema_version: 1

context:
  name: moonup
  version: "0.3.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/chawyehsu/moonup/archive/refs/tags/v${{ version }}.tar.gz
  sha256: c426f11eeadd4f25f02267af88b864c9363673ed53c5ad8e0b29badd17df28a8

build:
  number: 0
  skip:
    # remove when moonbit adds support for these targets
    - win and arm64
    - linux and aarch64
  script:
    # [win] disable default static linked executables
    - if: win
      then: del /S /Q .cargo\config.toml
    # Disable `self_update` feature for conda variant builds
    - cargo install --locked --root ${{ PREFIX }} --path . --no-track --no-default-features

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}
  host:
    - if: linux
      then: openssl

tests:
  - script:
      - moonup --help

about:
  homepage: https://github.com/chawyehsu/moonup
  license: Apache-2.0
  license_file: LICENSE
  summary: "Manage multiple MoonBit installations"
  description: "Moonup is a version manager for MoonBit"
  repository: https://github.com/chawyehsu/moonup

extra:
  recipe-maintainers:
    - chawyehsu
