schema_version: 1

context:
  name: moonup
  version: "0.5.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/chawyehsu/moonup/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 63b619e2bd040c3efba5edfa0fcffa241e4b33f70809e7ab52662fbbf839d5fd

build:
  number: 0
  skip:
    # remove when moonbit adds support for these targets
    - win and arm64
  script:
    env:
      # Use cmake to build aws-lc-sys, because conda's CFLAGS inject -O2 which
      # overrides the -O0 required by jitterentropy-base.c, causing a build failure.
      AWS_LC_SYS_CMAKE_BUILDER: "1"
    content:
      - if: win
        # [win] disable default static linked executables;
        # Avoid Windows path-length issue breaking Cmake/Cargo
        then: |
          del /S /Q .cargo\config.toml
          for %%I in ("%SRC_DIR%") do set DRIVE_LETTER=%%~dI
          set "CARGO_TARGET_DIR=%DRIVE_LETTER%\cd"
          set "CARGO_HOME=%DRIVE_LETTER%\ch"
      # Disable `self_update` feature for conda variant builds
      - cargo auditable install --locked --root ${{ PREFIX }} --path . --no-track --no-default-features
      - cargo-bundle-licenses --format yaml --output ${{ SRC_DIR }}/THIRDPARTY.yml

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}
    - cargo-auditable
    - cargo-bundle-licenses
    - cmake
    - if: osx
      # ld64 is needed otherwise below error raises:
      # ld: -lto_library library filename must be 'libLTO.dylib'
      then: ld64
  host:
    - if: linux
      then: openssl

tests:
  - script:
      - moonup --help

about:
  homepage: https://github.com/chawyehsu/moonup
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Manage multiple MoonBit installations
  description: Moonup is a version manager for MoonBit
  repository: https://github.com/chawyehsu/moonup

extra:
  recipe-maintainers:
    - chawyehsu
