context:
  version: "0.149.1"

package:
  name: codex
  version: ${{ version }}

source:
  url: https://github.com/openai/codex/archive/refs/tags/rust-v${{ version }}.tar.gz
  sha256: 85139f405ce455bf14ff452615cdb2572d752e31a1e0da6891ac8325915d10ce

build:
  number: 0
  skip:
    - unix
    - win and x86_64
  script:
    file: build
    env:
      # Use cmake to build aws-lc-sys, because conda's CFLAGS inject -O2 which
      # overrides the -O0 required by jitterentropy-base.c, causing a build failure.
      AWS_LC_SYS_CMAKE_BUILDER: "1"

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - cmake
    - just
    - if: linux
      then: pkg-config
    - if: win
      then: m2-sed
  host:
    - if: linux
      then:
        - openssl <4.0a0
        - libcap

tests:
  - script:
      - if: build_platform == target_platform
        then: codex --version
  - package_contents:
      bin:
        - codex
        - codex-code-mode-host
      files:
        - etc/pixi/codex/global-ignore-conda-prefix

about:
  summary: Lightweight coding agent that runs in your terminal
  homepage: https://github.com/openai/codex
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
    - zelosleone
    - Hofer-Julian
    - pavelzw
